name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.18
softdepend: [ Vault, ItemsAdder, PlaceholderAPI, AdvancedGUI, DiscordSRV ]
depend: CustomCooking
authors: [ bounser ]
description: Market valuations in minecraft