name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.18
softdepend: [ Vault, PlaceholderAPI, AdvancedGUI, DiscordSRV ]
depend: [ CustomCooking, ItemsAdder ]
authors: [ bounser ]
description: Market valuations in minecraft